FROM ubuntu:16.04

ENV hostworkdir /home/huma
WORKDIR ${hostworkdir}   # WORKDIR /workspace

RUN apt-get update
RUN apt-get install -y sudo
RUN sudo apt-get install -y curl
RUN sudo apt-get install -y docker 
RUN sudo apt-get install -y docker-compose
RUN sudo apt-get install -y golang 
RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
RUN sudo apt-get install -y nodejs
RUN sudo npm install npm@5.6.0 -g 

CMD curl -sSL http://bit.ly/2ysbOFE | bash -s -- 1.4.3 1.4.3 0.4.15 -s

