FROM ubuntu:16.04

# Create app directory
WORKDIR /workdir

RUN sudo apt-get update && sudo apt-get install docker && sudo apt-get install docker-compose && sudo apt-get install golang && sudo apt-get install nodejs && sudo apt-get install npm && sudo npm install npm@5.6.0 -g && sudo usermod -a -G docker $USER

